fetch 2j48
color green,  resi 0
color green,  resi 1
color blue,  resi 2
color blue,  resi 3
color blue,  resi 4
color blue,  resi 5
color blue,  resi 6
color green,  resi 7
color green,  resi 8
color green,  resi 9
color red,  resi 10
color red,  resi 11
color red,  resi 12
color red,  resi 13
color red,  resi 14
color red,  resi 15
color red,  resi 16
color red,  resi 17
color red,  resi 18
color red,  resi 19
color red,  resi 20
color red,  resi 21
color red,  resi 22
color green,  resi 23
color green,  resi 24
color green,  resi 25
color blue,  resi 26
color blue,  resi 27
color blue,  resi 28
color blue,  resi 29
color blue,  resi 30
color blue,  resi 31
color green,  resi 32
color green,  resi 33
color green,  resi 34
color green,  resi 35
color red,  resi 36
color red,  resi 37
color red,  resi 38
color red,  resi 39
color red,  resi 40
color red,  resi 41
color red,  resi 42
color green,  resi 43
color green,  resi 44
color green,  resi 45
color blue,  resi 46
color blue,  resi 47
color blue,  resi 48
color blue,  resi 49
color blue,  resi 50
color blue,  resi 51
color green,  resi 52
color green,  resi 53
color green,  resi 54
color green,  resi 55
color red,  resi 56
color red,  resi 57
color red,  resi 58
color red,  resi 59
color red,  resi 60
color red,  resi 61
color red,  resi 62
color red,  resi 63
color red,  resi 64
color red,  resi 65
color red,  resi 66
color red,  resi 67
color red,  resi 68
color red,  resi 69
color green,  resi 70
color green,  resi 71
color green,  resi 72
color green,  resi 73
color green,  resi 74
color green,  resi 75
color green,  resi 76
color green,  resi 77
color blue,  resi 78
color blue,  resi 79
color blue,  resi 80
color blue,  resi 81
color green,  resi 82
color green,  resi 83
color green,  resi 84
color green,  resi 85
color green,  resi 86
color green,  resi 87
color red,  resi 88
color red,  resi 89
color red,  resi 90
color red,  resi 91
color red,  resi 92
color red,  resi 93
color red,  resi 94
color red,  resi 95
color red,  resi 96
color red,  resi 97
color red,  resi 98
color green,  resi 99
color green,  resi 100
color green,  resi 101
color green,  resi 102
color green,  resi 103
color green,  resi 104
color red,  resi 105
color red,  resi 106
color blue,  resi 107
color blue,  resi 108
color blue,  resi 109
color green,  resi 110
color green,  resi 111
color green,  resi 112
color green,  resi 113
color green,  resi 114
color green,  resi 115
color green,  resi 116
color green,  resi 117
color green,  resi 118
color green,  resi 119
color green,  resi 120
